### PR TITLE
feat: add plugin args

### PR DESCRIPTION
**Pull request by jason-liew**
- support plugin args for logical replication
- add pglogical outputPlugin example
- similar code with pgx before v4.0

### CODE REVIEW

**Comment by tzachshabtay** [comment]
@jackc can this be merged in? Without this we're forced to use `test_decoding` which isn't really meant to be used in production afaik.

**Comment by tzachshabtay** [comment]
@jason-liew also a question on your example, I noticed that you used `pglogical` as your plugin. As far as I know `pgoutput` is the built in plugin since postgres 10, right? i.e what would be the reason of choosing `pglogical` over `pgoutput`?

**Comment by jackc** [comment]
The code appears okay but the example using "pglogical" as output plugin doesn't work for me.

```
jack@glados ~/dev/pglogrepl/example/pglogrepl_demo ±jason-liew-add_plugin_args⚡ » PGLOGREPL_DEMO_CONN_STRING="postgres://pglogrepl:secret@127.0.0.1/pglogrepl?replication=database" go run main.go                                     1 ↵
2020/03/07 10:23:46 SystemID: 6763282523296379061 Timeline: 1 XLogPos: A/3B775138 DBName: pglogrepl
2020/03/07 10:23:46 CreateReplicationSlot failed: ERROR: could not access file "pglogical": No such file or directory (SQLSTATE 58P01)
exit status 1
```

This is on PG 12. It works if I switch back to the "test_decoding" plugin.

**Comment by jason-liew** [comment]
@tzachshabtay AWS Database Migration Service use pglogical plugin to sync data. I was learning to setup this plugin and test it with golang code.

**Comment by jason-liew** [comment]
@jackc Maybe your PG 12 have not  install the pglogical plugin.  I've add pgoutput example now.
```CREATE PUBLICATION pglogrepl_demo FOR ALL TABLES;```

**Comment by tzachshabtay** [comment]
@jason-liew if publications is a requirement, maybe you should create it as part of the sample code..

**Pull request merged**
