### PR TITLE
Timeline history and Handling CopyDone

### PR DESCRIPTION
**Pull request by sebasmannem**
While adding functionality to wal-g for streaming wal using pglogrepl,
I ran into the following 2 missing functionalities:
1: There was no implementation to add TIMELINE_HISTORY functionality to pglogrepl. This is the first commit.
2: ending a copy-both situation requires sending a CopyDone from client and receiving a final CopyDoneResult. This is the second commit.

The second commit relies on [this PR on pgconn](https://github.com/jackc/pgconn/pull/48).
With these changes, streaming wal using pglogrepl physical SR works on wal-g.

### CODE REVIEW

**Comment by sebasmannem** [comment]
I checked the failed checks, and it needs a merge of [this PR on pgconn](https://github.com/jackc/pgconn/pull/48) first.

**Comment by sebasmannem** [comment]
I have added some unittests, and an example program for physical replication.
I tested the unit tests locally, and they work.
Please note that:
* the test postgres used by travis probably does not have any timeline increased (running on tl 1).
That skips one test, which is the most important. Would be great if we could advance the timeline, but that requires some magic at init time, (creating a .signal file, restarting postgres and running pg_ctl promote), so that probably is not easy to add.
* Sending CopyDone is done in 2 cases:
  1: client wants to stop SR, that is implemented in unit tests and works as hoped for
  2: server reaches end of this timeline. I don't think we an test that case properly

Furthermore, this PR will only work if we can also use github.com/jackc/pgconn@master, so I was hoping you could help me with upgrading to that.

**Comment by sebasmannem** [comment]
Btw, Before you merge, let me test this new implementation with wal-g too.

**Comment by jackc** [comment]
I'm not very familiar with the physical protocol, but that said, it looks good to me.

I just pushed a branch with a couple tweaks: https://github.com/jackc/pglogrepl/commits/sebasmannem-timeline_history

I bumped the pgconn dependency to master so I could run the tests. I'll update that to a tagged release next time pgconn has a release. I also changed the test with the `replication=on` parameter so it works whether `PGLOGREPL_TEST_CONN_STRING` is a URL or a DSN.

Let me know when your finished with the wal-g test and I'll merge it.

**Comment by sebasmannem** [comment]
I tested against wal-g, and ran into an issue.
I applied some changes, and now all woks fine for when server first sends CopyDone (end of timeline - wal-g), and for when client first sends CopyDone (as implemented in unit test).
I rebased with your changes, and we are good ;)

**Comment by jackc** [comment]
Thanks!

**Pull request merged**
